version: '2'
services:
        frontend:
                build: .
                command: serve -s ./build -p 3000
                volumes: 
                        - ./usr/app/
                        - /usr/app/node_modules
                        - /usr/app/build
                ports:
                        - "3000:3000"
