version: '2'
services:
        frontend:
                build: .
                command: serve -s ./build -p 3000
                volumes: 
                        - ./usr/app/
                        - /usr/app/node_modules
                        - /usr/app/build
                ports:
                        - "3000:3000"
                environment:
                        - REACT_APP_API_URL=https://www.emdrremoto.com.br:3002
                        - REACT_APP_CREATE_ROOM_URL=https://www.emdrremoto.com.br:3002/daily/new-room
                        - REACT_APP_WEBSOCKET_URL=https://www.emdrremoto.com.br:3001
                        - REACT_APP_DAILY_CO_API=https://sistemas3xp.daily.co
