export const contatos = [
    {foto: "", nome: "Fillipe"},
    {foto: "", nome: "Queiroz"},
    {foto: "", nome: "Gabriel"},
    {foto: "", nome: "Matheus"},
    {foto: "", nome: "Nunes"},
    {foto: "", nome: "Vinicius"},
    {foto: "", nome: "Cid"},
    {foto: "", nome: "Rapha"},
    {foto: "", nome: "Saulo"},
    {foto: "", nome: "Fillipe"},
    {foto: "", nome: "Fillipe"},
    {foto: "", nome: "Fillipe"},
    {foto: "", nome: "Fillipe"},
    {foto: "", nome: "Fillipe"},
    {foto: "", nome: "Fillipe"},
    {foto: "", nome: "Fillipe"},
]