let options: any;
export default options = [{"option":"93","name":"AFEGANISTAO"},
{"option":"27","name":"AFRICA DOUL"},
{"option":"1","name":"ALASCA"},
{"option":"355","name":"ALBANIA"},
{"option":"49","name":"ALEMANHA"},
{"option":"376","name":"ANDORRA"},
{"option":"244","name":"ANGOLA"},
{"option":"1","name":"ANGUILLA"},
{"option":"599","name":"ANT.HOLANDESAS"},
{"option":"1","name":"ANTIGUA"},
{"option":"966","name":"ARABIAAUDITA"},
{"option":"213","name":"ARGELIA"},
{"option":"54","name":"ARGENTINA"},
{"option":"374","name":"ARMENIA"},
{"option":"297","name":"ARUBA"},
{"option":"247","name":"ASCENSAO ILHAS"},
{"option":"61","name":"AUSTRALIA"},
{"option":"43","name":"AUSTRIA"},
{"option":"994","name":"AZERBAIJAO"},
{"option":"1","name":"BAHAMAS"},
{"option":"880","name":"BANGLADESH"},
{"option":"1","name":"BARBADOS"},
{"option":"973","name":"BAREIN"},
{"option":"375","name":"BELARUS"},
{"option":"32","name":"BELGICA"},
{"option":"501","name":"BELIZE"},
{"option":"229","name":"BENIN"},
{"option":"1","name":"BERMUDAS"},
{"option":"591","name":"BOLIVIA"},
{"option":"387","name":"BOSNIA E HERZEGOVINA"},
{"option":"267","name":"BOTSUANA"},
{"option":"55","name":"BRASIL"},
{"option":"673","name":"BRUNEI"},
{"option":"359","name":"BULGARIA"},
{"option":"226","name":"BURKINA FASO"},
{"option":"257","name":"BURUNDI"},
{"option":"975","name":"BUTAO"},
{"option":"238","name":"CABO VERDE"},
{"option":"237","name":"CAMAROES"},
{"option":"855","name":"CAMPUCHEA"},
{"option":"1","name":"CANADA"},
{"option":"7","name":"CASAQUISTAO"},
{"option":"974","name":"CATAR"},
{"option":"1","name":"CAYMAN ILHAS"},
{"option":"235","name":"CHADE"},
{"option":"56","name":"CHILE"},
{"option":"86","name":"CHINA"},
{"option":"357","name":"CHIPRE"},
{"option":"65","name":"CINGAPURA"},
{"option":"57","name":"COLOMBIA"},
{"option":"269","name":"COMORES"},
{"option":"242","name":"CONGO"},
{"option":"682","name":"COOK ILHAS"},
{"option":"850","name":"COREIA DOORTE"},
{"option":"82","name":"COREIA DOUL"},
{"option":"225","name":"COSTA DO MARFIM"},
{"option":"506","name":"COSTA RICA"},
{"option":"385","name":"CROACIA"},
{"option":"53","name":"CUBA"},
{"option":"246","name":"DIEGO GARCIA"},
{"option":"45","name":"DINAMARCA"},
{"option":"253","name":"DJIBUTI"},
{"option":"1","name":"DOMINICA"},
{"option":"1","name":"DOMINICANA REP"},
{"option":"20","name":"EGITO"},
{"option":"503","name":"ELALVADOR"},
{"option":"971","name":"EMIRADOS A. UNIDOS"},
{"option":"593","name":"EQUADOR"},
{"option":"291","name":"ERITREA"},
{"option":"386","name":"ESLOVENIA"},
{"option":"34","name":"ESPANHA"},
{"option":"1","name":"ESTADOS UNIDOS"},
{"option":"372","name":"ESTONIA"},
{"option":"251","name":"ETIOPIA"},
{"option":"298","name":"FAROE ILHAS"},
{"option":"679","name":"FIJI"},
{"option":"63","name":"FILIPINAS"},
{"option":"358","name":"FINLANDIA"},
{"option":"886","name":"FORMOSA"},
{"option":"33","name":"FRANCA"},
{"option":"241","name":"GABAO"},
{"option":"220","name":"GAMBIA"},
{"option":"233","name":"GANA"},
{"option":"995","name":"GEORGIA"},
{"option":"350","name":"GIBRALTAR"},
{"option":"1","name":"GRANADA"},
{"option":"30","name":"GRECIA"},
{"option":"299","name":"GROENLANDIA"},
{"option":"590","name":"GUADALUPE"},
{"option":"1","name":"GUAM"},
{"option":"502","name":"GUATEMALA"},
{"option":"592","name":"GUIANA"},
{"option":"594","name":"GUIANA FRANCESA"},
{"option":"224","name":"GUINE"},
{"option":"240","name":"GUINE EQUATORIAL"},
{"option":"245","name":"GUINE-BISSAU"},
{"option":"509","name":"HAITI"},
{"option":"1","name":"HAVAI"},
{"option":"31","name":"HOLANDA"},
{"option":"504","name":"HONDURAS"},
{"option":"852","name":"HONG KONG"},
{"option":"36","name":"HUNGRIA"},
{"option":"967","name":"IEMEN REP."},
{"option":"91","name":"INDIA"},
{"option":"62","name":"INDONESIA"},
{"option":"98","name":"IRA"},
{"option":"964","name":"IRAQUE"},
{"option":"353","name":"IRLANDA"},
{"option":"354","name":"ISLANDIA"},
{"option":"972","name":"ISRAEL"},
{"option":"39","name":"ITALIA"},
{"option":"1","name":"JAMAICA"},
{"option":"81","name":"JAPAO"},
{"option":"962","name":"JORDANIA"},
{"option":"686","name":"KIRIBATI"},
{"option":"965","name":"KUWEIT"},
{"option":"856","name":"LAOS"},
{"option":"266","name":"LESOTO"},
{"option":"371","name":"LETONIA"},
{"option":"961","name":"LIBANO"},
{"option":"231","name":"LIBERIA"},
{"option":"218","name":"LIBIA"},
{"option":"423","name":"LIECHTENSTEIN"},
{"option":"370","name":"LITUANIA"},
{"option":"352","name":"LUXEMBURGO"},
{"option":"853","name":"MACAU"},
{"option":"389","name":"MACEDONIA"},
{"option":"261","name":"MADAGASCAR"},
{"option":"60","name":"MALASIA"},
{"option":"265","name":"MALAVI"},
{"option":"960","name":"MALDIVAS"},
{"option":"223","name":"MALI"},
{"option":"356","name":"MALTA"},
{"option":"500","name":"MALVINAS ILHAS"},
{"option":"1","name":"MARIANASORTE ISL."},
{"option":"212","name":"MARROCOS"},
{"option":"692","name":"MARSHALL ILHAS"},
{"option":"596","name":"MARTINICA"},
{"option":"230","name":"MAURICIO"},
{"option":"222","name":"MAURITANIA"},
{"option":"269","name":"MAYOTTE(ILHAS)"},
{"option":"52","name":"MEXICO"},
{"option":"691","name":"MICRONESIA"},
{"option":"838","name":"MIDWAY ILHAS"},
{"option":"258","name":"MOCAMBIQUE"},
{"option":"373","name":"MOLDOVA"},
{"option":"976","name":"MONGOLIA"},
{"option":"382","name":"MONTENEGRO"},
{"option":"1","name":"MONTSERRAT"},
{"option":"264","name":"NAMIBIA"},
{"option":"674","name":"NAURU"},
{"option":"977","name":"NEPAL"},
{"option":"505","name":"NICARAGUA"},
{"option":"227","name":"NIGER"},
{"option":"234","name":"NIGERIA"},
{"option":"683","name":"NIUE"},
{"option":"672","name":"NORFOLK ILHA"},
{"option":"47","name":"NORUEGA"},
{"option":"687","name":"NOVA CALEDONIA"},
{"option":"64","name":"NOVA ZELANDIA"},
{"option":"968","name":"OMA"},
{"option":"680","name":"PALAU"},
{"option":"970","name":"PALESTINA"},
{"option":"507","name":"PANAMA"},
{"option":"675","name":"PAPUAOVA GUINE"},
{"option":"92","name":"PAQUISTAO"},
{"option":"595","name":"PARAGUAI"},
{"option":"51","name":"PERU"},
{"option":"48","name":"POLONIA"},
{"option":"1","name":"PORTO RICO"},
{"option":"351","name":"PORTUGAL"},
{"option":"377","name":"PRINCIPADO MONACO"},
{"option":"254","name":"QUENIA"},
{"option":"996","name":"QUIRGUIZIA"},
{"option":"44","name":"REINO UNIDO"},
{"option":"236","name":"REP.CENTRO AFRICANA"},
{"option":"421","name":"REP.ESLOVAQUIA"},
{"option":"420","name":"REP.TCHECA"},
{"option":"262","name":"REUNIAO ILHAS"},
{"option":"854","name":"RODRIGUES ILHAS"},
{"option":"40","name":"ROMENIA"},
{"option":"250","name":"RUANDA"},
{"option":"7","name":"RUSSIA"},
{"option":"1","name":"S.KITTS &NEVIS"},
{"option":"1","name":"S.VICENTE ILHAS"},
{"option":"833","name":"SAARA ESPANHOL"},
{"option":"677","name":"SALOMAO ILHAS"},
{"option":"685","name":"SAMOA"},
{"option":"684","name":"SAMOA AMERICANA"},
{"option":"1","name":"SANTA LUCIA"},
{"option":"378","name":"SAO MARINO"},
{"option":"239","name":"SAO TOME E PRINCIPE"},
{"option":"221","name":"SENEGAL"},
{"option":"232","name":"SERRA LEOA"},
{"option":"381","name":"SÃ�RVIA"},
{"option":"248","name":"SEYCHELLES"},
{"option":"963","name":"SIRIA"},
{"option":"252","name":"SOMALIA"},
{"option":"94","name":"SRI-LANKA"},
{"option":"508","name":"ST.PIERRE E MIQUELON"},
{"option":"290","name":"STA HELENA ILHAS"},
{"option":"268","name":"SUAZILANDIA"},
{"option":"249","name":"SUDAO"},
{"option":"46","name":"SUECIA"},
{"option":"41","name":"SUICA"},
{"option":"597","name":"SURINAME"},
{"option":"992","name":"TADJIQUISTAO"},
{"option":"66","name":"TAILANDIA"},
{"option":"689","name":"TAITI"},
{"option":"255","name":"TANZANIA"},
{"option":"672","name":"TERRIT.EXT.AUSTRALIA"},
{"option":"670","name":"TIMOR LESTE"},
{"option":"228","name":"TOGO"},
{"option":"676","name":"TONGA"},
{"option":"690","name":"TOQUELAU"},
{"option":"1","name":"TRINIDAD E TOBAGO"},
{"option":"216","name":"TUNISIA"},
{"option":"993","name":"TURCOMENIA"},
{"option":"1","name":"TURKS E CAICOS ILHAS"},
{"option":"90","name":"TURQUIA"},
{"option":"688","name":"TUVALU"},
{"option":"380","name":"UCRANIA"},
{"option":"256","name":"UGANDA"},
{"option":"95","name":"UNIAO DE MYANMAR"},
{"option":"598","name":"URUGUAI"},
{"option":"998","name":"UZBEQUISTAO"},
{"option":"678","name":"VANUATU"},
{"option":"58","name":"VENEZUELA"},
{"option":"84","name":"VIETNA"},
{"option":"1","name":"VIRGENS A. ILHAS"},
{"option":"1","name":"VIRGENS B.ILHAS"},
{"option":"839","name":"WAKE ILHAS"},
{"option":"681","name":"WALLIS E FUTUNA"},
{"option":"243","name":"ZAIRE"},
{"option":"260","name":"ZAMBIA"},
{"option":"259","name":"ZANZIBAR"},
{"option":"263","name":"ZIMBABUE"}
]